### ISSUE TITLE
[Bug]: App writes "false" regardless of taxi status

### ISSUE THREAD

**Issue by Dom733** [IBXCODECAT/Saber-Metrics#62]
### What happened?

When choosing whether a robot has taxi'd or not, the app writes false regardless of what you chose
Robot has taxi'd => false
Robot hasn't tax'd => false

### Version

0.0 (InDev)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by IBXCODECAT** [comment]
Was autocasted to a Button instead of a toggle Button :)

**Comment by IBXCODECAT** [comment]
All fixed ;)
