### ISSUE TITLE
[Bug]: Unoptimized GUI

### ISSUE THREAD

**Issue by IBXCODECAT** [IBXCODECAT/Saber-Metrics#93]
### What happened?

The GUI is currently not optimized due to all elements of the GUI being in one activity. Activity fragments would allow for easier UI handling as it is a more modular design.

### Version

0.0 (InDev)

### What devices are you seeing the problem on?

Tablet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dom733** [comment]
Currently working on this. As of this comment (3/12 12:24pm), the counter fragment is complete but not implemented, and hence not tested. I currently don't know how to do that but I'll figure it out.

**Comment by IBXCODECAT** [comment]
It appears that we are no longer going to be using fragments anyway... You reverted the changes?
